image: yarn:1.22.4

pipelines:
  deafault:
    - step:
        name: Install dependencies
        caches:
          - yarn
        script:
          - yarn install

    - parallel:
      - step:
          name: Check linting
          caches:
            - yarn
          script:
            - yarn lint
      - step:
        name: Check build
        caches:
            - yarn
        script:
            - yarn build