name : "Xweather"
image: yarn:1.22.4
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      caches:
        - yarn
      run: yarn install
    - name: Check linting
      run: yarn lint
    - name: Check build
      run: yarn build
    
