name : "Xweather"
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: yarn install
    - name: Check linting
      run: yarn lint
    - name: Check build
      run: yarn build
    
