name : "Xweather"
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        yarn install && CI=false yarn lint && yarn build
    
