name : "Xweather"
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: yarn install
    - name: Check linting
      run: vue-cli-service lint
    - name: Check build
      run: vue-cli-service build
    
